<?php
declare(strict_types=1);
function sp_b64u(string $s): string { return rtrim(strtr(base64_encode($s), '+/', '-_'), '='); }
function sp_b64ud(string $s): string|false { return base64_decode(strtr($s, '-_', '+/') . str_repeat('=', (4-strlen($s)%4)%4), true); }
function sp_der_int(string $bytes): string { $bytes=ltrim($bytes,"\0"); if ($bytes==='' ) $bytes="\0"; if ((ord($bytes[0]) & 0x80)!==0) $bytes="\0".$bytes; return "\x02".chr(strlen($bytes)).$bytes; }
function sp_der_sig_to_raw(string $der): string { $i=2; if (ord($der[1]) & 0x80) $i=2+(ord($der[1])&0x7f); if (ord($der[$i])!==2) throw new RuntimeException('Invalid ECDSA signature'); $lr=ord($der[$i+1]); $r=substr($der,$i+2,$lr); $i += 2+$lr; if (ord($der[$i])!==2) throw new RuntimeException('Invalid ECDSA signature'); $ls=ord($der[$i+1]); $s=substr($der,$i+2,$ls); return str_pad(ltrim($r,"\0"),32,"\0",STR_PAD_LEFT).str_pad(ltrim($s,"\0"),32,"\0",STR_PAD_LEFT); }
function sp_vapid_jwt(string $endpoint, array $cfg): string { $u=parse_url($endpoint); $aud=($u['scheme']??'https').'://'.$u['host'].(isset($u['port'])?':'.$u['port']:''); $header=sp_b64u(json_encode(['typ'=>'JWT','alg'=>'ES256'])); $payload=sp_b64u(json_encode(['aud'=>$aud,'exp'=>time()+3600,'sub'=>$cfg['vapid_subject']])); $input=$header.'.'.$payload; $key=openssl_pkey_get_private($cfg['vapid_private_pem']); if(!$key || !openssl_sign($input,$sig,$key,OPENSSL_ALGO_SHA256)) throw new RuntimeException('VAPID signing failed'); return $input.'.'.sp_b64u(sp_der_sig_to_raw($sig)); }
function sp_import_p256_public(string $raw) { $prefix=hex2bin('3059301306072A8648CE3D020106082A8648CE3D030107034200'); $pem="-----BEGIN PUBLIC KEY-----\n".chunk_split(base64_encode($prefix.$raw),64,"\n")."-----END PUBLIC KEY-----\n"; $key=openssl_pkey_get_public($pem); if(!$key) throw new RuntimeException('Invalid P-256 public key'); return $key; }
function sp_encrypt_payload(array $subscription, array $payload): string { $userPub=sp_b64ud((string)$subscription['keys']['p256dh']); $auth=sp_b64ud((string)$subscription['keys']['auth']); if($userPub===false||strlen($userPub)!==65||$auth===false) throw new RuntimeException('Invalid subscription keys'); $peer=sp_import_p256_public($userPub); $ephemeral=openssl_pkey_new(['private_key_type'=>OPENSSL_KEYTYPE_EC,'curve_name'=>'prime256v1']); if(!$ephemeral) throw new RuntimeException('Cannot create ephemeral key'); $details=openssl_pkey_get_details($ephemeral); $serverPub="\x04".str_pad($details['ec']['x'],32,"\0",STR_PAD_LEFT).str_pad($details['ec']['y'],32,"\0",STR_PAD_LEFT); $shared=openssl_pkey_derive($peer,$ephemeral,32); if($shared===false) throw new RuntimeException('ECDH failed'); $ikm=hash_hkdf('sha256',$shared,32,"WebPush: info\0".$userPub.$serverPub,$auth); $salt=random_bytes(16); $cek=hash_hkdf('sha256',$ikm,16,"Content-Encoding: aes128gcm\0",$salt); $nonce=hash_hkdf('sha256',$ikm,12,"Content-Encoding: nonce\0",$salt); $plain=json_encode($payload,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_INVALID_UTF8_SUBSTITUTE)."\x02"; $tag=''; $cipher=openssl_encrypt($plain,'aes-128-gcm',$cek,OPENSSL_RAW_DATA,$nonce,$tag,'',16); if($cipher===false) throw new RuntimeException('Payload encryption failed'); return $salt.pack('N',4096).chr(strlen($serverPub)).$serverPub.$cipher.$tag; }
function sp_send_push(array $subscription, array $payload, array $cfg): int { if(!function_exists('curl_init')) throw new RuntimeException('PHP cURL extension required for sending push'); $endpoint=(string)$subscription['endpoint']; $body=sp_encrypt_payload($subscription,$payload); $jwt=sp_vapid_jwt($endpoint,$cfg); $headers=['TTL: 60','Content-Type: application/octet-stream','Content-Encoding: aes128gcm','Authorization: vapid t='.$jwt.', k='.$cfg['vapid_public']]; $ch=curl_init($endpoint); curl_setopt_array($ch,[CURLOPT_POST=>true,CURLOPT_POSTFIELDS=>$body,CURLOPT_HTTPHEADER=>$headers,CURLOPT_RETURNTRANSFER=>true,CURLOPT_CONNECTTIMEOUT=>8,CURLOPT_TIMEOUT=>15,CURLOPT_SSL_VERIFYPEER=>true,CURLOPT_SSL_VERIFYHOST=>2,CURLOPT_PROTOCOLS=>CURLPROTO_HTTPS,CURLOPT_FOLLOWLOCATION=>false]); curl_exec($ch); $status=(int)curl_getinfo($ch,CURLINFO_RESPONSE_CODE); $err=curl_error($ch); curl_close($ch); if($status===0) throw new RuntimeException('Push request failed: '.$err); return $status; }
